<?php

/**
 * @file
 * Main file of i18n_content_pane module.
 */

/**
 * Loads ctools custom content by name.
 */
function i18n_content_pane_load($content_name) {
  ctools_include('export');
  $pane = ctools_export_crud_load('ctools_custom_content', $content_name);

  return i18n_content_pane_get_object($pane);
}

/**
 * Loads list of ctools custom contents.
 */
function i18n_content_pane_list() {
  ctools_include('export');
  $panes = ctools_export_crud_load_all('ctools_custom_content');
  $objects = array_map('i18n_content_pane_get_object', $panes);

  return $objects;
}

/**
 * Build the object for translation from the ctools custom content.
 *
 * @param array $content
 *   Ctools Content loaded by ctools_export_crud_load() function.
 *
 * @return object
 *   Object prepared for translation.
 */
function i18n_content_pane_get_object($content) {
  $properties = array(
    'name' => $content->name,
    'title' => $content->settings['title'],
    'body' => $content->settings['body'],
    'format' => $content->settings['format'],
  );
  return (object)$properties;
}

/**
 * Translate the given Ctools content.
 *
 * @param array $content
 *   Ctools Content loaded by ctools_export_crud_load() function.
 *
 * @return mixed
 *   Object with translated properties of the Ctools content.
 */
function i18n_content_pane_translate($content) {
  $object = i18n_content_pane_get_object($content);
  $translation_object = i18n_string_object_translate('content_pane', $object);
  return $translation_object;
}
